// fe-sweets/src/App.vue
<template>
	<div class="item" v-for="(item, i) in shop" :key="i">
		{{item.name}}
		<button v-on:click="order(item)"
		> 
			Order Case : {{item.casesize}}
		</button>
		{{item.currency}} €
		{{item.price}}
		<button v-on:click="sell(item)"
		>
			Sell
		</button>
		Stock quantity: {{item.quantity}}
	</div>
<button v-if="count < 1" v-on:click="updateShop()"
>
	Open Shop
</button>
<div v-if="shop.length > 1">
	Stock Total Value : € {{total}}
</div>
</template>

<script>
import axios from 'axios';

export default {
	name: "App",
	methods: {
		updateShop() {
			this.shop = [];
			this.count = 0;
			this.count ++;
			this.subTotal();
			axios.get(`http://localhost:5000/stock`).then(res => {
				res.data.data.forEach((item)=> {
					this.shop.push(item);
				});
			});
		},
		sell(item) {
			axios.delete(`http://localhost:5000/${item.id}`).then(
				this.updateShop()
			);
		},
		order(item) {
			axios.post(`http://localhost:5000/${item.id}/restock`).then(
				this.updateShop()
			);
		},
		subTotal() {
			axios.get(`http://localhost:5000/value`).then(res => {
				this.total = res.data;
			});
		}
	},
	data() {
		return {
			count: 0,
			shop: [],
			total: ""
		};
	}
}
</script>

<style>
.item {
  padding: 1rem;
}
</style>

// fe-svelte-sweets/src/App.svelte
{#if count < 1}
	Shop
	<button on:click={updateShop}>
		Open Shop
	</button>
{/if}
{#each shop as item}
	<div class="item">
		{item.name}
		<button on:click={order(item)}>
			Order Case : {item.caseSize}
		</button>
		{item.currency} €
		{item.price}
		<button on:click={sell(item)}>
			Sell
		</button>
		Stock quantity: {item.quantity}
	</div>
{/each}
<div>
	Stock Total Value: € {total}
</div>


<script>
import axios from 'axios';

let shop = [];
let total = "";
let count = 0;

const updateShop = () => {
	count = 0;
	count ++;
	subTotal();
	axios.get(`http://localhost:8000/stock`).then(res => {
				shop = res.data;
	})
};
const sell = (item) => {
	axios.delete(`http://localhost:8000/${item.id}`).then(
		updateShop()
	);
};
const order = (item) => {
	axios.post(`http://localhost:8000/${item.id}/restock`).then(
		updateShop()
	);
};
const subTotal = () => {
	axios.get(`http://localhost:8000/value`).then(res => {
				total = res.data;
	});
};


</script>

<style>
.item{
	padding: 1rem;
}
</style>
